steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/kobold-wally-registry/wally-frontend:$COMMIT_SHA', '-f', 'wally-registry-frontend/Dockerfile', './wally-registry-frontend']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kobold-wally-registry/wally-frontend']

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "private-registry-frontend",
        "--image",
        "gcr.io/kobold-wally-registry/wally-frontend:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
 machineType: 'E2_HIGHCPU_8'
